[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
[[plugins]]
  package = "@netlify/plugin-lighthouse"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true